language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - gcc-7
      - g++-7

before_install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz -O premake.tar.gz
  - tar -xf premake.tar.gz
  - chmod +x premake5
install: 

script:
  - ./premake5 gmake2
  - make

